### PR TITLE
Update lol.js

### PR DESCRIPTION
**Pull request by Cp-022**

### CODE REVIEW

**Comment by Cp-022** [comment]
lol

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Comment by smoott** [comment]
Hello Cp-022 , Thank you for creating an issue. I am a bot, the owner will look into it soon

**Pull request closed without merging**
